root: ./docs/

redirects:  
    features/session-management-and-restoration: features/sessions/README.md
    features/session-management/session-restoration: features/sessions/session-restoration.md
    features/session-management/launch-configurations: features/sessions/launch-configurations.md
    features/session-management/session-navigation: features/sessions/session-navigation.md
    features/warp-ai/ai-command-search: features/warp-ai/ai-command-suggestions.md
    features/ai-command-search: features/warp-ai/ai-command-suggestions.md
    features/workflows: features/entry/workflows.md
    features/command-search: features/entry/command-search.md
    features/command-history: features/entry/command-history.md
    features/hotkey-window: features/windows/global-hotkey.md
    features/tabs: features/windows/tabs.md
    features/split-panes: features/windows/split-panes.md
    features/themes: appearance/themes.md
    features/themes/custom-themes: appearance/custom-themes.md
    features/compact-mode: appearance/compact-mode.md
    features/appearance/themes: appearance/themes.md
    features/appearance/custom-themes: appearance/custom-themes.md
    features/appearance/prompt: features/prompt.md
    features/appearance/compact-mode: appearance/compact-mode.md
    features/linux: features/linux.md
    features/subshells: features/warpify/subshells.md
    features/ssh: features/warpify/ssh-legacy.md
    appearance/transparency-and-blurring: appearance/opacity-blurring-dimming.md
