#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime
from datetime import timezone
from pathlib import Path
from typing import Sequence

from common import DEFAULT_WORK_DIR
from common import DEFAULT_ONCALL_RESOLVER_SCRIPT
from common import docs_repo_root
from common import eprint

TASK_ORDER = ["warp_app_update", "changelog", "licenses", "telemetry"]
COAUTHOR_LINE = "Co-Authored-By: Oz <oz-agent@warp.dev>"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run release update scripts in order, with optional task selection.",
    )
    parser.add_argument(
        "--tasks",
        nargs="+",
        choices=TASK_ORDER,
        default=TASK_ORDER.copy(),
        help="Subset of tasks to run (default: all tasks in order).",
    )
    parser.add_argument(
        "--docs-repo",
        default=None,
        help="Path to docs repo root (auto-detected if omitted).",
    )
    parser.add_argument(
        "--work-dir",
        default=str(DEFAULT_WORK_DIR),
        help=f"Working directory for intermediate artifacts (default: {DEFAULT_WORK_DIR})",
    )
    parser.add_argument(
        "--manifest",
        default=None,
        help="Artifact manifest path (default: <work-dir>/warp_artifacts.json).",
    )
    parser.add_argument(
        "--channel-versions-file",
        default=None,
        help="Path to channel_versions.json for changelog update.",
    )
    parser.add_argument(
        "--channel-versions-repo",
        default=None,
        help="Path to channel-versions repo for changelog update.",
    )
    parser.add_argument(
        "--channel-versions-url",
        default=None,
        help="Fallback URL for channel versions if no local file is found.",
    )
    parser.add_argument(
        "--licenses-file",
        default=None,
        help="Explicit THIRD_PARTY_LICENSES.txt path for licenses update.",
    )
    parser.add_argument(
        "--telemetry-json-file",
        default=None,
        help="Explicit telemetry JSON path for telemetry update.",
    )
    parser.add_argument(
        "--telemetry-command",
        default=None,
        help="Explicit telemetry command string for telemetry update.",
    )
    parser.add_argument(
        "--skip-warp-app-extract",
        action="store_true",
        help="Skip AppImage extraction in warp_app_update (useful for non-Linux local tests).",
    )
    parser.add_argument(
        "--skip-dependency-preflight",
        action="store_true",
        help="Skip Linux telemetry dependency preflight in warp_app_update.",
    )
    parser.add_argument(
        "--auto-install-missing-dependency",
        action="store_true",
        help=(
            "If Linux telemetry dependency preflight fails, attempt package-manager "
            "installation (for supported distros)."
        ),
    )
    parser.add_argument(
        "--create-pr",
        action="store_true",
        help=(
            "After tasks finish, commit changes, push branch, and create or update a "
            "pull request."
        ),
    )
    parser.add_argument(
        "--allow-dirty-repo",
        action="store_true",
        help=(
            "Allow running with pre-existing uncommitted changes when --create-pr is set. "
            "Use with caution."
        ),
    )
    parser.add_argument(
        "--skip-pr-commit",
        action="store_true",
        help="Skip creating a commit before PR creation (requires no uncommitted changes).",
    )
    parser.add_argument(
        "--skip-pr-push",
        action="store_true",
        help="Skip pushing the branch before PR creation.",
    )
    parser.add_argument(
        "--commit-message",
        default=None,
        help="Commit subject to use when --create-pr creates a commit.",
    )
    parser.add_argument(
        "--pr-base",
        default="main",
        help="Base branch for PR create/update (default: main).",
    )
    parser.add_argument(
        "--pr-title",
        default=None,
        help="Explicit PR title (defaults to a dated release-updates title).",
    )
    parser.add_argument(
        "--pr-body-file",
        default=None,
        help="Path to PR body markdown file (defaults to autogenerated body).",
    )
    parser.add_argument(
        "--pr-draft",
        action="store_true",
        help="Create pull requests as draft.",
    )
    parser.add_argument(
        "--pr-auto-merge",
        action="store_true",
        help=(
            "Enable auto-merge (squash) on the PR after creation and mark it ready "
            "for review. Requires --create-pr. Incompatible with --pr-draft."
        ),
    )
    parser.add_argument(
        "--assign-oncall-reviewer",
        "--assign-oncall-reviewers",
        dest="assign_oncall_reviewers",
        action="store_true",
        help=(
            "Resolve on-call reviewers (primary + secondary when available) and "
            "assign them to the PR."
        ),
    )
    parser.add_argument(
        "--oncall-schedule-id",
        dest="oncall_schedule_ids",
        action="append",
        default=[],
        help=(
            "Grafana IRM schedule ID used to resolve on-call reviewers. "
            "Repeat this flag to resolve reviewers from multiple schedules "
            "(for example, primary + secondary)."
        ),
    )
    parser.add_argument(
        "--oncall-max-reviewers",
        type=int,
        default=2,
        help="Maximum number of on-call users to assign as reviewers (default: 2).",
    )
    parser.add_argument(
        "--oncall-resolver-script",
        default=str(DEFAULT_ONCALL_RESOLVER_SCRIPT),
        help=(
            "Path to on-call reviewer resolver helper "
            f"(default: {DEFAULT_ONCALL_RESOLVER_SCRIPT})."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run all scripts in dry-run mode.",
    )
    return parser.parse_args()


def _run_script(script_path: Path, script_args: list[str]) -> None:
    command = [sys.executable, str(script_path), *script_args]
    eprint(f"Running: {' '.join(command)}")
    subprocess.run(command, check=True)  # nosec B603


def _run_command(
    command: list[str],
    *,
    cwd: Path,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(  # nosec B603
        command,
        cwd=cwd,
        check=False,
        capture_output=True,
        text=True,
    )
    if check and result.returncode != 0:
        stderr_or_stdout = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(
            "Command failed "
            f"({' '.join(command)}):\n"
            f"{stderr_or_stdout}",
        )
    return result


def _git_porcelain_status(repo_path: Path) -> list[str]:
    result = _run_command(
        ["git", "--no-pager", "status", "--porcelain"],
        cwd=repo_path,
    )
    return [line for line in result.stdout.splitlines() if line.strip()]


def _git_changed_files(repo_path: Path) -> list[str]:
    changed_files: list[str] = []
    for line in _git_porcelain_status(repo_path=repo_path):
        if len(line) < 4:
            continue
        changed_files.append(line[3:].strip())
    return changed_files


def _git_current_branch(repo_path: Path) -> str:
    result = _run_command(
        ["git", "--no-pager", "rev-parse", "--abbrev-ref", "HEAD"],
        cwd=repo_path,
    )
    branch = result.stdout.strip()
    if not branch:
        raise RuntimeError("Could not determine current git branch.")
    return branch


def _ahead_commit_count(repo_path: Path, base_branch: str) -> int:
    base_ref = f"origin/{base_branch}"
    fetch_result = _run_command(
        ["git", "fetch", "origin", base_branch],
        cwd=repo_path,
        check=False,
    )
    if fetch_result.returncode != 0:
        base_ref = base_branch

    result = _run_command(
        ["git", "--no-pager", "rev-list", "--left-right", "--count", f"{base_ref}...HEAD"],
        cwd=repo_path,
    )
    counts = result.stdout.strip().split()
    if len(counts) != 2:
        raise RuntimeError(f"Unexpected rev-list output: {result.stdout.strip()}")
    return int(counts[1])


def _commit_all_changes(repo_path: Path, commit_message: str) -> None:
    _run_command(["git", "add", "-A"], cwd=repo_path)
    _run_command(
        ["git", "commit", "-m", commit_message, "-m", COAUTHOR_LINE],
        cwd=repo_path,
    )


def _push_branch(repo_path: Path, branch_name: str) -> None:
    _run_command(
        ["git", "push", "--set-upstream", "origin", branch_name],
        cwd=repo_path,
    )


def _find_existing_pr_url(repo_path: Path) -> str | None:
    result = _run_command(
        ["gh", "pr", "view", "--json", "url", "--jq", ".url"],
        cwd=repo_path,
        check=False,
    )
    if result.returncode != 0:
        return None
    pr_url = result.stdout.strip()
    return pr_url or None


def _ensure_coauthor_line(body: str) -> str:
    trimmed = body.rstrip()
    if COAUTHOR_LINE not in trimmed:
        trimmed = f"{trimmed}\n\n{COAUTHOR_LINE}"
    return trimmed + "\n"


def _default_pr_title() -> str:
    date_stamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    return f"docs: weekly release updates ({date_stamp})"


def _default_pr_body(*, ordered_tasks: Sequence[str], changed_files: Sequence[str]) -> str:
    lines: list[str] = [
        "## Summary",
        f"- Ran `release_updates` tasks in order: {', '.join(ordered_tasks)}.",
    ]

    if changed_files:
        lines.append("- Updated files:")
        for changed_file in changed_files[:25]:
            lines.append(f"  - `{changed_file}`")
        if len(changed_files) > 25:
            lines.append(f"  - ...and {len(changed_files) - 25} more")
    else:
        lines.append("- No working-tree file changes were detected in this run.")

    lines.extend(
        [
            "",
            "## Validation",
            "- Ran the release update scripts successfully.",
            "",
            # This is a real, direct PR-creation code path (not delegated to
            # create_pr), so it carries the same v1 doc-quality contract
            # sections every other PR-producing skill does. Changelog/license/
            # telemetry updates are generated verbatim from their source of
            # record, which is the allowlisted "low" category for generated data.
            "## Documentation risk",
            "Risk: low",
            "Rationale: Changelog/license/telemetry entries generated verbatim from "
            "channel_versions.json / the license scan / the telemetry command; no "
            "hand-authored product claim.",
            "Docs override: none",
            "",
            "## Unverified claims",
            "None \u2014 generated data copied from its source of record.",
        ],
    )
    return _ensure_coauthor_line("\n".join(lines))


def _load_pr_body(
    *,
    pr_body_file: str | None,
    ordered_tasks: Sequence[str],
    changed_files: Sequence[str],
) -> str:
    if pr_body_file:
        body_path = Path(pr_body_file).expanduser().resolve()
        if not body_path.exists():
            raise FileNotFoundError(f"--pr-body-file not found: {body_path}")
        body = body_path.read_text(encoding="utf-8")
        return _ensure_coauthor_line(body)

    return _default_pr_body(
        ordered_tasks=ordered_tasks,
        changed_files=changed_files,
    )


def _create_or_update_pull_request(
    *,
    repo_path: Path,
    base_branch: str,
    pr_title: str,
    pr_body: str,
    pr_draft: bool,
) -> str:
    existing_pr_url = _find_existing_pr_url(repo_path=repo_path)
    if existing_pr_url:
        _run_command(
            [
                "gh",
                "pr",
                "edit",
                existing_pr_url,
                "--base",
                base_branch,
                "--title",
                pr_title,
                "--body",
                pr_body,
                "--add-label",
                "warpy-factory",
            ],
            cwd=repo_path,
        )
        return existing_pr_url

    command = [
        "gh",
        "pr",
        "create",
        "--base",
        base_branch,
        "--title",
        pr_title,
        "--body",
        pr_body,
        "--label",
        "warpy-factory",
    ]
    if pr_draft:
        command.append("--draft")
    result = _run_command(command, cwd=repo_path)
    for line in reversed(result.stdout.splitlines()):
        candidate = line.strip()
        if candidate.startswith("http://") or candidate.startswith("https://"):
            return candidate
    raise RuntimeError(
        "Could not parse PR URL from gh output.\n"
        f"{result.stdout.strip()}",
    )


def _resolve_oncall_reviewers(
    *,
    resolver_script: Path,
    schedule_ids: Sequence[str],
    max_reviewers: int,
    repo_path: Path,
) -> list[str]:
    if not resolver_script.exists():
        raise FileNotFoundError(
            "On-call resolver script not found: "
            f"{resolver_script}",
        )

    normalized_schedule_ids: list[str] = []
    for raw_schedule_id in schedule_ids:
        for candidate in str(raw_schedule_id).split(","):
            schedule_id = candidate.strip()
            if schedule_id and schedule_id not in normalized_schedule_ids:
                normalized_schedule_ids.append(schedule_id)

    if not normalized_schedule_ids:
        raise RuntimeError("No on-call schedule IDs were provided.")

    per_schedule_reviewer_limit = max(1, max_reviewers)
    if len(normalized_schedule_ids) > 1:
        per_schedule_reviewer_limit = 1

    resolved_reviewers: list[str] = []
    for schedule_id in normalized_schedule_ids:
        result = _run_command(
            [
                sys.executable,
                str(resolver_script),
                schedule_id,
                "--max-reviewers",
                str(per_schedule_reviewer_limit),
            ],
            cwd=repo_path,
            check=False,
        )
        if result.returncode == 0:
            raw_stdout = result.stdout.strip()
            if not raw_stdout:
                raise RuntimeError(
                    "On-call resolver succeeded but returned no stdout "
                    f"(schedule: {schedule_id}).",
                )
            payload = json.loads(raw_stdout)
            reviewers_raw = payload.get("reviewers")
            if not isinstance(reviewers_raw, list):
                raise RuntimeError(
                    "On-call resolver succeeded but did not return reviewer list "
                    f"(schedule: {schedule_id}).",
                )
            reviewers = [
                str(reviewer).strip()
                for reviewer in reviewers_raw
                if str(reviewer).strip()
            ]
            if not reviewers:
                raise RuntimeError(
                    "On-call resolver succeeded but returned empty reviewer list "
                    f"(schedule: {schedule_id}).",
                )
            for reviewer in reviewers:
                if reviewer not in resolved_reviewers:
                    resolved_reviewers.append(reviewer)
            continue

        stderr = result.stderr.strip()
        stdout = result.stdout.strip()
        details = "\n".join(part for part in [stderr, stdout] if part)
        if result.returncode == 2:
            raise RuntimeError(
                "On-call reviewer resolution was ambiguous "
                f"(schedule: {schedule_id}). "
                "Please resolve manually or update matching overrides.\n"
                f"{details}",
            )
        raise RuntimeError(
            "On-call reviewer resolution failed "
            f"(schedule: {schedule_id}).\n"
            f"{details}",
        )

    if not resolved_reviewers:
        raise RuntimeError("Could not resolve any on-call reviewers.")
    return resolved_reviewers[: max(1, max_reviewers)]


def _assign_reviewers(
    *,
    repo_path: Path,
    pr_url: str,
    reviewers: Sequence[str],
) -> None:
    for reviewer in reviewers:
        _run_command(
            ["gh", "pr", "edit", pr_url, "--add-reviewer", reviewer],
            cwd=repo_path,
        )


def _enable_auto_merge(
    *,
    repo_path: Path,
    pr_url: str,
) -> None:
    # Mark ready for review first (required before auto-merge can be enabled).
    _run_command(
        ["gh", "pr", "ready", pr_url],
        cwd=repo_path,
    )
    _run_command(
        ["gh", "pr", "merge", "--auto", "--squash", pr_url],
        cwd=repo_path,
    )


def _validate_args(args: argparse.Namespace) -> None:
    normalized_schedule_ids: list[str] = []
    for raw_schedule_id in args.oncall_schedule_ids:
        for candidate in str(raw_schedule_id).split(","):
            schedule_id = candidate.strip()
            if schedule_id and schedule_id not in normalized_schedule_ids:
                normalized_schedule_ids.append(schedule_id)
    args.oncall_schedule_ids = normalized_schedule_ids
    if args.assign_oncall_reviewers and not args.create_pr:
        raise ValueError("--assign-oncall-reviewer requires --create-pr.")
    if args.assign_oncall_reviewers and not args.oncall_schedule_ids:
        raise ValueError(
            "--assign-oncall-reviewer requires --oncall-schedule-id.",
        )
    if args.pr_auto_merge and not args.create_pr:
        raise ValueError("--pr-auto-merge requires --create-pr.")
    if args.pr_auto_merge and args.pr_draft:
        raise ValueError("--pr-auto-merge is incompatible with --pr-draft.")


def _maybe_create_pr(
    *,
    args: argparse.Namespace,
    docs_root: Path,
    ordered_tasks: Sequence[str],
) -> None:
    if not args.create_pr:
        return

    branch_name = _git_current_branch(repo_path=docs_root)
    if branch_name == args.pr_base:
        raise RuntimeError(
            f"Current branch ({branch_name}) matches --pr-base ({args.pr_base}). "
            "Switch to a feature branch before creating a PR.",
        )

    changed_files = _git_changed_files(repo_path=docs_root)
    changed_files_for_pr_body = changed_files.copy()
    if changed_files and args.skip_pr_commit:
        raise RuntimeError(
            "--skip-pr-commit was set, but there are uncommitted file changes. "
            "Commit changes first or rerun without --skip-pr-commit.",
        )

    if changed_files and not args.skip_pr_commit and not args.dry_run:
        commit_message = (
            args.commit_message
            or f"docs: weekly release updates ({datetime.now(tz=timezone.utc).strftime('%Y-%m-%d')})"
        )
        _commit_all_changes(
            repo_path=docs_root,
            commit_message=commit_message,
        )
        changed_files = _git_changed_files(repo_path=docs_root)

    ahead_count = _ahead_commit_count(
        repo_path=docs_root,
        base_branch=args.pr_base,
    )
    if ahead_count == 0:
        eprint(
            "No commits ahead of base branch; skipping PR create/update.",
        )
        return

    reviewers: list[str] = []
    if args.assign_oncall_reviewers:
        reviewers = _resolve_oncall_reviewers(
            resolver_script=Path(args.oncall_resolver_script).expanduser().resolve(),
            schedule_ids=args.oncall_schedule_ids,
            max_reviewers=int(args.oncall_max_reviewers),
            repo_path=docs_root,
        )
        eprint(
            "Resolved on-call reviewers: "
            + ", ".join(f"@{reviewer}" for reviewer in reviewers),
        )

    pr_title = args.pr_title or _default_pr_title()
    pr_body = _load_pr_body(
        pr_body_file=args.pr_body_file,
        ordered_tasks=ordered_tasks,
        changed_files=changed_files_for_pr_body,
    )

    if args.dry_run:
        if not args.skip_pr_push:
            eprint(f"[dry-run] Would push branch: {branch_name}")
        eprint(
            "[dry-run] Would create or update pull request "
            f"(base={args.pr_base}, title={pr_title!r})",
        )
        if reviewers:
            eprint(
                "[dry-run] Would assign reviewers: "
                + ", ".join(f"@{reviewer}" for reviewer in reviewers),
            )
        if args.pr_auto_merge:
            eprint("[dry-run] Would enable auto-merge (squash) on PR.")
        return

    if not args.skip_pr_push:
        _push_branch(repo_path=docs_root, branch_name=branch_name)

    pr_url = _create_or_update_pull_request(
        repo_path=docs_root,
        base_branch=args.pr_base,
        pr_title=pr_title,
        pr_body=pr_body,
        pr_draft=args.pr_draft,
    )
    eprint(f"Pull request ready: {pr_url}")

    if reviewers:
        _assign_reviewers(
            repo_path=docs_root,
            pr_url=pr_url,
            reviewers=reviewers,
        )
        eprint(
            "Assigned reviewers to PR: "
            + ", ".join(f"@{reviewer}" for reviewer in reviewers),
        )

    if args.pr_auto_merge:
        _enable_auto_merge(repo_path=docs_root, pr_url=pr_url)
        eprint(f"Auto-merge (squash) enabled on PR: {pr_url}")


def main() -> int:
    args = parse_args()
    _validate_args(args=args)
    selected = set(args.tasks)
    ordered_tasks = [task for task in TASK_ORDER if task in selected]
    scripts_dir = Path(__file__).resolve().parent
    docs_root = docs_repo_root(explicit_docs_repo=args.docs_repo)
    work_dir = Path(args.work_dir).expanduser().resolve()
    manifest_path = (
        Path(args.manifest).expanduser().resolve()
        if args.manifest
        else work_dir / "warp_artifacts.json"
    )

    if not ordered_tasks:
        eprint("No tasks selected.")
        return 0
    if args.create_pr and not args.allow_dirty_repo and _git_porcelain_status(
        repo_path=docs_root,
    ):
        raise RuntimeError(
            "Repository has uncommitted changes before running release updates. "
            "Commit or stash them, or rerun with --allow-dirty-repo.",
        )

    for task in ordered_tasks:
        if task == "warp_app_update":
            script_args = [
                "--work-dir",
                str(work_dir),
                "--manifest",
                str(manifest_path),
            ]
            if args.skip_warp_app_extract:
                script_args.append("--skip-extract")
            if args.skip_dependency_preflight:
                script_args.append("--skip-dependency-preflight")
            if args.auto_install_missing_dependency:
                script_args.append("--auto-install-missing-dependency")
            if args.dry_run:
                script_args.append("--dry-run")
            _run_script(
                script_path=scripts_dir / "update_warp_app.py",
                script_args=script_args,
            )

        elif task == "changelog":
            script_args = ["--docs-repo", str(docs_root)]
            if args.channel_versions_file:
                script_args.extend(["--channel-versions-file", args.channel_versions_file])
            if args.channel_versions_repo:
                script_args.extend(["--channel-versions-repo", args.channel_versions_repo])
            if args.channel_versions_url:
                script_args.extend(["--channel-versions-url", args.channel_versions_url])
            if args.dry_run:
                script_args.append("--dry-run")
            _run_script(
                script_path=scripts_dir / "update_changelog.py",
                script_args=script_args,
            )

        elif task == "licenses":
            script_args = [
                "--docs-repo",
                str(docs_root),
                "--work-dir",
                str(work_dir),
                "--manifest",
                str(manifest_path),
            ]
            if args.licenses_file:
                script_args.extend(["--licenses-file", args.licenses_file])
            if args.dry_run:
                script_args.append("--dry-run")
            _run_script(
                script_path=scripts_dir / "update_licenses.py",
                script_args=script_args,
            )

        elif task == "telemetry":
            script_args = [
                "--docs-repo",
                str(docs_root),
                "--work-dir",
                str(work_dir),
                "--manifest",
                str(manifest_path),
            ]
            if args.telemetry_json_file:
                script_args.extend(["--telemetry-json-file", args.telemetry_json_file])
            if args.telemetry_command:
                script_args.extend(["--telemetry-command", args.telemetry_command])
            if args.dry_run:
                script_args.append("--dry-run")
            _run_script(
                script_path=scripts_dir / "update_telemetry.py",
                script_args=script_args,
            )

    eprint(f"Completed tasks: {', '.join(ordered_tasks)}")
    _maybe_create_pr(
        args=args,
        docs_root=docs_root,
        ordered_tasks=ordered_tasks,
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # noqa: BLE001
        eprint(f"ERROR: {exc}")
        raise SystemExit(1) from exc
