root: ./

redirects:
    platform/warp-platform: README.md
    developers/cli: cli/README.md
    platform/cli: cli/README.md
    integrations/integrations-overview/integrations-and-environments: cli/integrations-and-environments.md
    developers/cli#api-key-authentication: cli/README.md#api-key-authentication

